const U='https://qmmidefgdflbgbihhdah.supabase.co',K='sb_publishable_4OOU5jtcv3niED36n8j3ag_kB8b4t6Y',sb=supabase.createClient(U,K),$=id=>document.getElementById(id),DK='maty-kama-device',AK='maty-kama-attempt',NK='maty-kama-name';
const deviceId=localStorage.getItem(DK)||crypto.randomUUID();localStorage.setItem(DK,deviceId);let attemptId=localStorage.getItem(AK),nickname=localStorage.getItem(NK)||'',questions=[],answered=new Set(),points=0;
function show(id){['start','home','question','duplicate','done'].forEach(x=>$(x).classList.toggle('hidden',x!==id))}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function load(){const{data,error}=await sb.from('quiz_questions').select('id,order_no,question,options').eq('active',true).order('order_no');if(error)throw error;questions=data||[]}
async function refreshProgress(){if(!attemptId)return;const{data,error}=await sb.rpc('get_quiz_progress',{p_attempt_id:attemptId});if(error){if(String(error.message||'').includes('invalid_attempt')){localStorage.removeItem(AK);localStorage.removeItem(NK);attemptId=null;nickname='';answered=new Set();points=0;return}throw error}const r=data?.[0]||{};answered=new Set(r.answered_ids||[]);points=Number(r.points||0);updateScore()}
function updateScore(){const found=answered.size;$('foundCount').textContent=found;$('pointsCount').textContent=points;$('status').textContent=`${found} / ${questions.length}`;$('homeHint').textContent=found>=questions.length?'Máš hotovo! 🎉':'Hledej další QR kód a pokračuj ve hře!'}
function renderQuestionResult(q,value,correct,correctValue){const opts=typeof q.options==='string'?JSON.parse(q.options):q.options;const selectedLabel=opts.find(o=>o.value===value)?.label||value;const correctLabel=opts.find(o=>o.value===correctValue)?.label||correctValue;document.querySelectorAll('.option').forEach(b=>{b.classList.remove('picked','right','wrong');if(b.dataset.value===value)b.classList.add('picked',correct?'right':'wrong');if(b.dataset.value===correctValue)b.classList.add('right')});$('questionMessage').innerHTML=correct?`<div class="answer-result right-result"><strong>SPRÁVNĚ! 🎉</strong><span>Tvoje odpověď: ${esc(selectedLabel)}</span></div>`:`<div class="answer-result wrong-result"><strong>ŠPATNĚ 😅</strong><span>Tvoje odpověď: ${esc(selectedLabel)}</span><span>Správná odpověď: <b>${esc(correctLabel)}</b></span></div>`}
async function start(){const name=$('nickname').value.trim();$('startError').textContent='';if(name.length<2){$('startError').textContent='Zadej přezdívku alespoň na 2 znaky.';return}const id=crypto.randomUUID(),{error}=await sb.from('quiz_attempts').insert({id,nickname:name,device_id:deviceId});if(error){$('startError').textContent=error.code==='23505'?'Toto zařízení nebo přezdívka už kvíz absolvovaly.':'Start se nepodařil. Zkus to prosím znovu.';return}attemptId=id;nickname=name;localStorage.setItem(AK,id);localStorage.setItem(NK,name);await refreshProgress();const q=Number(new URLSearchParams(location.search).get('q'))||1;show('question');openQuestion(q)}
function openQuestion(id){const q=questions.find(x=>x.id===id||x.order_no===id);if(!q){$('questionText').textContent='Tato otázka není aktivní.';return}if(answered.has(q.id)){show('duplicate');return}$('questionNo').textContent=`OTÁZKA ${q.order_no}`;updateScore();$('questionText').textContent=q.question;const opts=typeof q.options==='string'?JSON.parse(q.options):q.options;$('options').innerHTML=opts.map(o=>`<button class="option" data-value="${esc(o.value)}"><span class="letter">${esc(o.value)}</span><span>${esc(o.label)}</span></button>`).join('');$('questionMessage').textContent='';document.querySelectorAll('.option').forEach(b=>b.onclick=()=>answer(q,b.dataset.value))}
async function answer(q,value){if(answered.has(q.id))return;document.querySelectorAll('.option').forEach(b=>b.disabled=true);const{data,error}=await sb.rpc('submit_quiz_answer',{p_attempt_id:attemptId,p_question_id:q.id,p_selected_value:value});if(error){if(String(error.message||'').includes('invalid_attempt')){localStorage.removeItem(AK);localStorage.removeItem(NK);attemptId=null;nickname='';answered=new Set();points=0;show('start');$('startError').textContent='Platnost hry vypršela. Zadej prosím přezdívku znovu.';return}if(String(error.message||'').includes('already_answered')){await refreshProgress();show('duplicate');return}$('questionMessage').textContent='Odpověď se nepodařilo uložit. Zkus QR načíst znovu.';document.querySelectorAll('.option').forEach(b=>b.disabled=false);return}answered.add(q.id);const result=data?.[0]||{};if(result.correct)points++;updateScore();renderQuestionResult(q,value,!!result.correct,result.correct_value);if(answered.size===questions.length)setTimeout(()=>{$('doneName').textContent=nickname;show('done')},2200)}
async function goHome(){await refreshProgress();if(!attemptId){show('start');return}updateScore();show('home')}
async function init(){try{await load()}catch(e){$('startError').textContent='Kvíz se nepodařilo načíst.';return}if(attemptId){nickname=localStorage.getItem(NK)||'';$('nickname').value=nickname;await refreshProgress();if(!attemptId){show('start');return}const q=Number(new URLSearchParams(location.search).get('q'));if(q){if(answered.has(questions.find(x=>x.id===q||x.order_no===q)?.id))show('duplicate');else{show('question');openQuestion(q)}}else show('home')}else show('start')}
$('startBtn').onclick=start;$('nickname').onkeydown=e=>{if(e.key==='Enter')start()};$('backHomeBtn').onclick=goHome;$('duplicateHomeBtn').onclick=goHome;$('doneScoreBtn').onclick=goHome;init();